### ISSUE TITLE
Posts duplicates

### ISSUE THREAD

**Issue by ThatOneCalculator** [VoltrexMaster/liveuamap-news#2] opened 2022-03-01 22:40 UTC
![image](https://user-images.githubusercontent.com/44733677/156260995-5ba0b8df-5cee-4257-84bf-810c10b674ca.png)

It does this a lot

**Comment by VoltrexKeyva** [comment] 2022-03-02 02:15
Can reproduce, this was caused because of the last ID of the news being written to the `config.json` file and not being read again, a fix is on the way.

Thank you for reporting!

**Comment by VoltrexKeyva** [comment] 2022-03-02 02:44
Fixed in ecaaffd5fe8b99850d2b6c220f7a841ef9f76ed1.

**Closed as completed by VoltrexKeyva** 2022-03-02 02:44 UTC

**Comment by ThatOneCalculator** [comment] 2022-03-03 03:45
@VoltrexMaster looks like it's happening again, I'm on the latest commit. 

![Screenshot_20220302-194442.jpg](https://user-images.githubusercontent.com/44733677/156492267-9514ad44-82dd-43a5-b17f-d9a6b32855de.jpg)

**Comment by VoltrexKeyva** [comment] 2022-03-03 03:48
@ThatOneCalculator possible that you're running multiple instances in some way?

I've been running the latest commit as of now (34816f3e00eebd7b9464e6dba0bd2262712e5b38) for hours and haven't encountered a single duplicate.

**Comment by ThatOneCalculator** [comment] 2022-03-03 04:27
> @ThatOneCalculator possible that you're running multiple instances in some way?
> 
> I've been running the latest commit as of now (34816f3e00eebd7b9464e6dba0bd2262712e5b38) for hours and haven't encountered a single duplicate.

No duplicate instances, and it was fine up until those messages

**Comment by VoltrexKeyva** [comment] 2022-03-03 04:39
> > @ThatOneCalculator possible that you're running multiple instances in some way?
> > I've been running the latest commit as of now ([34816f3](https://github.com/VoltrexMaster/liveuamap-news/commit/34816f3e00eebd7b9464e6dba0bd2262712e5b38)) for hours and haven't encountered a single duplicate.
> 
> No duplicate instances, and it was fine up until those messages

That's pretty strange, it's probably caused by the base [website](https://liveuamap.com/) duplicating the news sometimes. Other than that I don't see how the duplication could be occuring although I haven't encountered any duplicates myself, I'll have a look at it again.

**Comment by VoltrexKeyva** [comment] 2022-03-03 04:53
@ThatOneCalculator I found the reason why there are duplicates, it's because the base [website](https://liveuamap.com/) lists the previously posted news on top if they're edited, which is what causes them to be scrapped again and duplicated, as their IDs differ while the news might not be so different.

**Comment by ThatOneCalculator** [comment] 2022-03-03 04:57
Ah, is there a way to check the title and the ID to prevent this?

**Comment by VoltrexKeyva** [comment] 2022-03-03 06:32
> Ah, is there a way to check the title and the ID to prevent this?

I fixed the duplication of news entirely by storing the last 30 news and checking for them (https://github.com/VoltrexMaster/liveuamap-news/commit/008956a51acf68c2325992d786d31f6376ca9a6b).

**Comment by ThatOneCalculator** [comment] 2022-03-03 06:41
Wonderful, tysm!
